#!/bin/bash

data_file="data.json"

lower_name=$(jq -r '.name' "$data_file")
lower_type=$(jq -r '.types[0].type.name' "$data_file")
height=$(jq -r '.height' "$data_file")
weight=$(jq -r '.weight' "$data_file")

name=$(echo "$lower_name" | sed 's/./\u&/')
type=$(echo "$lower_type" | sed 's/./\u&/')

read -r formatted_height formatted_weight << EOF
$(awk -v h="$height" -v w="$weight" 'BEGIN {
    formatted_height = sprintf("%.1f", h / 10);
    formatted_weight = sprintf("%.1f", w / 10);

    print formatted_height, formatted_weight
}')
EOF

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
