#!/bin/bash

data_file="data.json"

name=$(cat $data_file | jq -r '.name')
height=$(cat $data_file | jq -r '.height')
weight=$(cat $data_file | jq -r '.weight')
type=$(cat $data_file | jq -r '.types[0].type.name')

formatted_height=$(bc <<< "scale=1; $height / 10.0")
formatted_weight=$(bc <<< "scale=1; $weight / 10.0")

echo "${name^} is of type ${type^}, has a height of weighs ${formatted_weight}kg and ${formatted_height}m"
